import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  variable: "--dm-sans",
  weight: ["100", "200", "300", "400", "600", "900"],
  subsets: ["latin"],
});
export const metadata = {
  title: "Nautilus Software",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
